spring.datasource:
  url: jdbc:h2:file:~/IdeaProjects/client-service/ClientService;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password:

spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate.ddl-auto: none
  generate-ddl: false
  properties.hibernate.hbm2ddl.auto: none

spring:
  application:
    name: ClientService
server:
  port: 8801
#eureka:
#  client:
#    service-url: 'http://localhost:7777/eureka/'